apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: git-ops
build:
  artifacts:
  - image: gcr.io/$PROJECT_ID/gitops-image
    docker:
      dockerfile: dockerfile
deploy:
  kubectl:
    manifests:
    - deployment.yaml